version: '2'
services:
  web:
    image: fpfis/httpd-php-dev:8.1
    working_dir: /var/www/html
    ports:
      - 8080:8080
    volumes:
      - .:/var/www/html # Non Mac users.
      # - nfsmount:/var/www/html # Mac Users with the nfsmount volume.
    environment:
      COMPOSERVER: "--2"
      XDEBUG_CONFIG: "remote_enable=1 remote_host=10.254.254.254 remote_port=9000 idekey=PHPSTORM remote_autostart=1"
      PHP_IDE_CONFIG: "serverName=Docker"
      # For Xdebug setup, run this command in the terminal:
      # For Mac users: sudo ifconfig en0 alias 10.254.254.254 255.255.255.0
      # For Linux users: sudo ip addr add 10.254.254.254/32 dev lo label lo:1
  mysql:
    image: percona/percona-server:5.7
    command: --innodb-log-file-size=1G --max_allowed_packet=1G --innodb-buffer-pool-size=512M --wait_timeout=3000 --net_write_timeout=3000 --log_error_verbosity=3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
#    ports:
#      - 3306:3306
  sparql:
    image: openeuropa/triple-store-dev
    environment:
      - SPARQL_UPDATE=true
      - DBA_PASSWORD=dba
    ports:
      - "8890:8890"
  # Visit localhost:7900 to access the browser.
  selenium:
    image: selenium/standalone-chrome:4.1.3-20220405
    environment:
      - DISPLAY=:99
      - SCREEN_WIDTH=1280
      - SCREEN_HEIGHT=800
      - VNC_NO_PASSWORD=1
    ports:
      - '7900:7900'
    shm_size: 2g

#### Mac users: uncomment the "volumes" key to enable the NFS file sharing. You can find more information about Docker for Mac here: https://github.com/openeuropa/openeuropa/blob/master/docs/starting/tooling.md#using-docker-on-macos

#volumes:
#  nfsmount:
#    driver: local
#    driver_opts:
#      type: nfs
#      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
#      device: ":${PWD}/"

#### End Mac users.
