<?php

/**
 * @file
 * OpenEuropa Corporate Blocks module.
 */

declare(strict_types = 1);

/**
 * Implements hook_theme().
 */
function oe_corporate_blocks_theme() {
  return [
    'oe_corporate_blocks_footer' => [
      'variables' => [
        'corporate_footer' => [],
        'custom_footer' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_modules_installed().
 */
function oe_corporate_blocks_modules_installed($modules) {
  if (!in_array('oe_multilingual', $modules)) {
    return;
  }

  // Triggers the config override localisation if the oe_multilingual is
  // installed. See also oe_corporate_blocks_install().
  _oe_corporate_blocks_ensure_config_translations();
}

/**
 * Ensures that local entries exist for the configuration translations.
 *
 * Because we are shipping with pre-existing config translations,
 * we need to also ensure that upon install, corresponding locale entries are
 * created for all the translatable values found in them. See
 * \Drupal\locale\LocaleConfigSubscriber for the logic that does this normally
 * and onto which we rely by simply saving the config translations.
 *
 * In addition, since the aforementioned logic only happens if the site is NOT
 * currently in the process of being installed, we need to "trick" it into
 * believing otherwise for the cases in which the module is being installed
 * as part of a site install (such as profile dependency).
 */
function _oe_corporate_blocks_ensure_config_translations(): void {
  $backup = isset($GLOBALS['install_state']) ? $GLOBALS['install_state'] : NULL;
  if ($backup) {
    unset($GLOBALS['install_state']);
  }

  $language_manager = \Drupal::languageManager();
  foreach ($language_manager->getLanguages() as $language) {
    if ($language->getId() === 'en') {
      continue;
    }

    /** @var \Drupal\language\ConfigurableLanguageInterface $config */
    $config = $language_manager->getLanguageConfigOverride($language->getId(), 'oe_corporate_blocks.data.footer');
    $config->save();
  }

  if ($backup) {
    $GLOBALS['install_state'] = $backup;
  }
}
