<?php

/**
 * @file
 * OpenEuropa Corporate Blocks module.
 */

declare(strict_types = 1);

/**
 * Implements hook_theme().
 */
function oe_corporate_blocks_theme() {
  return [
    'oe_corporate_blocks_footer' => [
      'variables' => [
        'corporate_footer' => [],
        'custom_footer' => [],
      ],
    ],
    'oe_corporate_blocks_eu_footer' => [
      'variables' => [
        'corporate_footer' => [],
        'custom_footer' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_locale_translation_projects_alter().
 */
function oe_corporate_blocks_locale_translation_projects_alter(&$projects) {
  $projects['oe_corporate_blocks']['info']['interface translation server pattern'] = drupal_get_path('module', 'oe_corporate_blocks') . '/translations/%project-%language.po';
}
